export const GET_PLANTS = 'getPlants'
export const GET_GROUPS = 'getGroups'
export const GET_AREAS = 'getAreas'
export const GET_GROUPTYPES = 'getGroupTypes'
export const GET_USEROLE = 'getUserRole'
export const GET_LIGHTCOLORS = 'getLightColors'